version: "3"

services:
  murdock:
    user: 0:0
    ports:
      - 8000:8000
    build:
      context: .
    image: ${MURDOCK_DOCKER_IMAGE}
    container_name: murdock-app
    environment:
        - MURDOCK_LOG_LEVEL
        - MURDOCK_BASE_URL
        - MURDOCK_USE_API_TOKEN
        - MURDOCK_API_TOKEN
        - MURDOCK_NUM_WORKERS
        - MURDOCK_DB_HOST=mongodb
        - MURDOCK_DB_PORT=27017
        - MURDOCK_DB_NAME
        - MURDOCK_GITHUB_APP_CLIENT_ID
        - MURDOCK_GITHUB_APP_CLIENT_SECRET
        - GITHUB_REPO
        - GITHUB_WEBHOOK_SECRET
        - GITHUB_API_TOKEN
        - CI_CANCEL_ON_UPDATE
        - CI_READY_LABEL
        - CI_FASTTRACK_LABELS
    volumes:
      - ${MURDOCK_ROOT_DIR}:/var/lib/murdock-data
      - ${MURDOCK_SCRIPTS_DIR}:/var/lib/murdock-scripts
    restart: always
  mongo:
    image: mongo:3.4
    container_name: mongodb
    ports:
        - 27017:27017
    command: [--smallfiles]
    volumes:
      - ${MONGODB_BD_DATA_DIR}:/data/db
    restart: always
