version: "3.9"

services:
  murdock:
    user: ${MURDOCK_USER_UID}:${MURDOCK_USER_GID}
    init: true
    build:
      context: .
      args:
        UID: ${MURDOCK_USER_UID}
        GID: ${MURDOCK_USER_GID}
    image: ${MURDOCK_DOCKER_IMAGE}
    container_name: murdock-app
    environment:
        - MURDOCK_LOG_LEVEL
        - MURDOCK_BASE_URL
        - MURDOCK_USE_JOB_TOKEN
        - MURDOCK_API_TOKEN
        - MURDOCK_NUM_WORKERS
        - MURDOCK_SCRIPT_NAME
        - MURDOCK_DB_HOST=mongodb
        - MURDOCK_DB_PORT=27017
        - MURDOCK_DB_NAME
        - MURDOCK_GITHUB_APP_CLIENT_ID
        - MURDOCK_GITHUB_APP_CLIENT_SECRET
        - GITHUB_REPO
        - GITHUB_WEBHOOK_SECRET
        - GITHUB_API_TOKEN
        - MURCOCK_CANCEL_ON_UPDATE
        - MURDOCK_ENABLE_COMMIT_STATUS
        - MURDOCK_COMMIT_STATUS_CONTEXT
        - MURDOCK_NOTIFIER_ENABLE
        - MURDOCK_NOTIFIER_PR_NOTIFIERS
        - MURDOCK_NOTIFIER_BRANCH_NOTIFIERS
        - MURDOCK_NOTIFIER_TAG_NOTIFIERS
        - MURDOCK_NOTIFIER_COMMIT_NOTIFIERS
        - MURDOCK_NOTIFIER_MAIL_RECIPIENTS
        - MURDOCK_NOTIFIER_MAIL_SERVER
        - MURDOCK_NOTIFIER_MAIL_PORT
        - MURDOCK_NOTIFIER_MAIL_USE_TLS
        - MURDOCK_NOTIFIER_MAIL_USERNAME
        - MURDOCK_NOTIFIER_MAIL_PASSWORD
        - MURDOCK_NOTIFIER_MATRIX_ROOM
        - MURDOCK_NOTIFIER_MATRIX_TOKEN
        - CI_READY_LABEL
        - CI_FASTTRACK_LABELS
    volumes:
      - ./murdock:/var/lib/murdock/murdock
      - ${MURDOCK_WORK_DIR}:/var/lib/murdock-data
      - ${MURDOCK_SCRIPTS_DIR}:/var/lib/murdock-scripts
      - ${MURDOCK_SSH_DIR}:/var/lib/murdock/.ssh:ro
      - ${MURDOCK_GITCACHE_DIR}:/.gitcache
    logging:
      driver: syslog
      options:
        tag: murdock-app
    networks: [$MURDOCK_DOCKER_NETWORK]
    restart: always
  webapp-build:
    image: node:16.9.1
    volumes:
      - ${MURDOCK_HTML_DIR}:/webapp
    environment:
      - REACT_APP_MURDOCK_HTTP_BASE_URL=${MURDOCK_BASE_URL}
      - REACT_APP_MURDOCK_WS_URL=${MURDOCK_WS_URL}
      - REACT_APP_NIGHTLIES_ROOT_URL=${MURDOCK_BASE_URL}
      - REACT_APP_MURDOCK_GITHUP_APP_CLIENT_ID=${MURDOCK_GITHUB_APP_CLIENT_ID}
      - REACT_APP_GITHUB_REPO=${GITHUB_REPO}
    command: >
      /bin/sh -c "
        cd /webapp &&
        npm install &&
        npm run build
      "
    profiles: ["setup"]
  webapp:
    user: ${MURDOCK_USER_UID}:${MURDOCK_USER_GID}
    build:
      context: webapp/.
      args:
        UID: ${MURDOCK_USER_UID}
        GID: ${MURDOCK_USER_GID}
    image: murdock-webapp
    container_name: murdock-webapp
    volumes:
      - ./webapp:/var/lib/murdock/webapp
      - ${MURDOCK_HTML_DIR}/build:/var/lib/murdock/webapp/build
    logging:
      driver: syslog
      options:
        tag: murdock-webapp
    networks: [$MURDOCK_DOCKER_NETWORK]
    restart: always
  mongo:
    image: mongo:4.2.16
    container_name: mongodb
    volumes:
      - ${MONGODB_BD_DATA_DIR}:/data/db
    logging:
      driver: syslog
      options:
        tag: murdock-mongo
    networks: [$MURDOCK_DOCKER_NETWORK]
    restart: always
  mongo-dev:
    image: mongo:4.2.16
    container_name: mongodb-dev
    ports:
      - 27017:27017
    volumes:
      - ${MONGODB_BD_DATA_DIR}:/data/db
    profiles: ["dev"]
  proxy:
    image: traefik:v2.5
    container_name: murdock-proxy
    ports:
      - ${MURDOCK_PORT}:8081
    volumes:
      - ${PWD}/traefik:/etc/traefik
    logging:
      driver: syslog
      options:
        tag: murdock-proxy
    networks: [$MURDOCK_DOCKER_NETWORK]
    restart: always
