version: "3.9"

services:
  murdock:
    user: 0:0
    build:
      context: .
    image: ${MURDOCK_DOCKER_IMAGE}
    container_name: murdock-app
    environment:
        - MURDOCK_LOG_LEVEL
        - MURDOCK_BASE_URL
        - MURDOCK_USE_JOB_TOKEN
        - MURDOCK_API_TOKEN
        - MURDOCK_NUM_WORKERS
        - MURDOCK_DB_HOST=mongodb
        - MURDOCK_DB_PORT=27017
        - MURDOCK_DB_NAME
        - MURDOCK_GITHUB_APP_CLIENT_ID
        - MURDOCK_GITHUB_APP_CLIENT_SECRET
        - GITHUB_REPO
        - GITHUB_WEBHOOK_SECRET
        - GITHUB_API_TOKEN
        - MURCOCK_CANCEL_ON_UPDATE
        - CI_READY_LABEL
        - CI_FASTTRACK_LABELS
    volumes:
      - ${MURDOCK_WORK_DIR}:/var/lib/murdock-data
      - ${MURDOCK_SCRIPTS_DIR}:/var/lib/murdock-scripts
    restart: always
  webapp-build:
    image: node:16.9.1
    volumes:
      - ${MURDOCK_HTML_DIR}:/webapp
    command: >
      /bin/sh -c "
        cd /webapp &&
        npm install && chown -R node:node node_modules &&
        REACT_APP_MURDOCK_GITHUP_APP_CLIENT_ID=${MURDOCK_GITHUB_APP_CLIENT_ID} REACT_APP_GITHUB_REPO=${GITHUB_REPO} npm run build &&
        chown -R node:node build
      "
    profiles: ["setup"]
  webapp:
    build:
      context: webapp/.
    image: murdock-webapp
    container_name: murdock-webapp
    volumes:
      - ${MURDOCK_HTML_DIR}/build:/var/lib/murdock/webapp/build
    restart: always
  mongo:
    image: mongo:4.2.16
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ${MONGODB_BD_DATA_DIR}:/data/db
    restart: always
  proxy:
    image: traefik:v2.5
    container_name: murdock-proxy
    ports:
      - ${MURDOCK_PORT}:8081
    volumes:
      - ${PWD}/traefik:/etc/traefik
    restart: always
