http:
  routers:
    to-murdock-api:
      rule: >
        PathPrefix(`/api`) ||
        PathPrefix(`/github`) ||
        PathPrefix(`/jobs`) ||
        PathPrefix(`/job`) ||
        PathPrefix(`/results`) ||
        PathPrefix(`/ws`) ||
        PathPrefix(`/openapi.json`)
      service: murdock
    to-webapp:
      middlewares:
        - "replace-regex"
      rule: >
        PathPrefix(`/`) ||
        PathPrefix(`/static`)
      service: webapp
  middlewares:
    replace-regex:
      replacePathRegex:
        regex: "^/details/(.*)"
        replacement: "/"

  services:
    webapp:
      loadBalancer:
        servers:
        - url: http://murdock-webapp:3000
    murdock:
      loadBalancer:
        servers:
        - url: http://murdock-app:8000
